rocketmq:
  testTopic: someTopic
  consumer:
    pull-batch-size: 1
    group:
      simbaOpenapiImport: com-guosen-platform-api-apiBackend-consumer-simbaOpenapiImport
  name-server: 192.168.109.146:9876
  producer:
    group: com-foresee-platform-api-producer
    sendMsgTimeout: 3000